### ISSUE TITLE
the script doesnt work.

### ISSUE THREAD

**Issue by SimonBauer-git** [SUFandom/debdroid#1]
u cloned the repo and the script doesnt work to extract/install debian.

**Comment by Mizumo-prjkt** [comment]
But did you do `cd debdroid`?

**Comment by Mizumo-prjkt** [comment]
![Screenshot_20220810-171411_Termux.jpg](https://user-images.githubusercontent.com/70519093/183876248-5d69affd-556e-4327-9279-11aa2592adac.jpg)

![Screenshot_20220810-171522_Termux.jpg](https://user-images.githubusercontent.com/70519093/183876269-667faff2-c888-4bc1-b345-f57b2d009076.jpg)

It should be like this

**Comment by Mizumo-prjkt** [comment]
## Warning

I think you shouldn't install right now atm because the issues are symlinks issues are making the os unusable at the moment, I'll make an update about it later

**Comment by Mizumo-prjkt** [comment]
I'll open this instead for newcomers

**Comment by SimonBauer-git** [comment]
thanks. i am the same guy as DoubleOwl7777 on reddidHolen Sie sich Outlook für Android

**Comment by Mizumo-prjkt** [comment]
Finally fixed  with Debdroid 1.5
